If an error occurs, the promise status changes from "pending" to a "rejected" (or failed) state. 

Promises give you the opportunity to handle the error with a method called catch().